# Generated by Django 4.2.7 on 2024-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantpermissions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertenantpermissions',
            name='extra_params',
            field=models.JSONField(blank=True, help_text='Extra parameters for the model', null=True),
        ),
        migrations.AddField(
            model_name='usertenantpermissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
